# Generated by Django 3.2.8 on 2022-12-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='appPoints',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='app',
            name='appImage',
            field=models.ImageField(upload_to='AppPics'),
        ),
    ]
