# Generated by Django 3.2.8 on 2022-12-14 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='taskCompleted',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
